#====================================================================== server-配置 ================#
server:
  port: 8899
  servlet:
    context-path: /account
  tomcat:
    uri-encoding: UTF-8
jhome:
  # 系统参数
  sysproperties:
    directoryPath: D:\GisData\
#====================================================================== spring-配置 =====================================#
spring:
  profiles:
    active: jdbc
    include: geoServerToolsService
  application:
    name: account-geoServerToolsService
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/mysqlDb?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc: true
  redis:
    host: 192.168.0.111
    database: 0
    port: 6379
    password: 123456
    timeout: 100000
    lettuce:
      pool:
        max-active:  1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#================================================================================  eureka配置 ================#
eureka:
  client:
    serviceUrl:
      defaultZone: http://daxunihao:123456@127.0.0.1:9100/account/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    #instanceId: ${spring.application.name}-${server.port} 任务链
    preferIpAddress: true
    ipAddress: 127.0.0.1
#    ipAddress: 10.1.20.58 #当前IP

feign:
  compression:
    request:
      enabled: true
      # 限制格式
      mimeTypes: text/xml,application/xml,application/json
      # 限制大小
      minRequestSize: 3000
    response:
      enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
#====================================================================== swagger2-配置 ===============#
swagger:
  enable: true

