#====================================================================== server-配置 ================#
server:
  port: 8891
  servlet:
    context-path: /account
  tomcat:
    uri-encoding: UTF-8
jhome:
  # 系统参数
  sysproperties:
    validPeriod: 1 #有效期（年）
    productCode: SD-INDT-009-SC-DS-00 #产品编码
#====================================================================== spring-配置 =====================================#
spring:
  profiles:
    active: jdbc
    include: configService
  application:
    name: account-configService
  datasource:
    url: jdbc:mysql://192.168.52.130:3306/mysqlDb?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc: true
  redis:
    host: 192.168.52.130
    database: 0
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active:  1000 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 300 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#====================================================================== swagger2-配置 ===============#
swagger:
  enable: true
